#!/usr/bin/env bash
# Writes the shared identity/conventions/build header to /tmp/agent-prompt.txt (overwrites).
# Reads env vars: ISSUE_NUMBER, ISSUE_TYPE, BRANCH, AGENT_EMAIL,
#                 CONVENTIONS, BUILD_CHECK, BUILD_TEST

set -euo pipefail

OUT=/tmp/agent-prompt.txt

cat > "$OUT" << EOF
You are an autonomous agent working on GitHub issue #${ISSUE_NUMBER} in the repository at the current working directory.

## Identity
- Issue type: ${ISSUE_TYPE}
- Branch: ${BRANCH}
- Working directory: this worktree (already checked out on ${BRANCH})
- Git commit identity: "Agent Coder <${AGENT_EMAIL}>"

## Universal rules (non-negotiable)
- Sign every commit: git commit -S
- No co-author lines, no "Generated by Claude" or "Claude Code" in commit or PR body
- Never touch .env or credential files
- Conventional commits: <type>(<scope>): <description>
- 0 warnings, 0 errors from the build check command before committing
EOF

# Project-specific conventions
if [ -n "${CONVENTIONS:-}" ]; then
  printf '\n## Project conventions\n\n%s\n' "$CONVENTIONS" >> "$OUT"
elif [ -f ".agentic/conventions.md" ]; then
  printf '\n## Project conventions\n\n' >> "$OUT"
  cat .agentic/conventions.md >> "$OUT"
fi

# Build commands
printf '\n## Build commands\n' >> "$OUT"
[ -n "${BUILD_CHECK:-}" ] && printf 'Check: %s\n' "$BUILD_CHECK" >> "$OUT"
[ -n "${BUILD_TEST:-}"  ] && printf 'Test:  %s\n' "$BUILD_TEST"  >> "$OUT"
[ -f ".agentic/build.sh" ] && printf 'Or run: .agentic/build.sh check|test\n' >> "$OUT"
