#!/usr/bin/env bash
# Build the agent prompt for a GitHub issue.
# Called from the GH Actions workflow; reads env vars:
#   ISSUE_NUMBER, ISSUE_TITLE, BRANCH, ISSUE_BODY,
#   BUILD_CHECK, BUILD_TEST, CONVENTIONS, AGENT_EMAIL
# Writes to: /tmp/agent-prompt.txt

set -euo pipefail

OUT=/tmp/agent-prompt.txt

# ── Base identity + conventions ──────────────────────────────────────────────
cat > "$OUT" << EOF
You are an autonomous coding agent fixing a GitHub issue in the repository at the current working directory.

## Identity
- You are Agent Coder for issue #${ISSUE_NUMBER}
- Branch: ${BRANCH}
- Working directory: this worktree (already checked out on ${BRANCH})
- Git commit identity: "Agent Coder <${AGENT_EMAIL}>"

## Universal conventions (non-negotiable)
- Sign every commit: git commit -S
- No co-author lines, no "Generated by Claude" or "Claude Code" in commit or PR body
- Never touch .env or credential files
- Conventional commits: <type>(<scope>): <description>
- 0 warnings, 0 errors from the build check command before committing
EOF

# ── Project-specific conventions ─────────────────────────────────────────────
if [ -n "${CONVENTIONS:-}" ]; then
  printf '\n## Project conventions\n\n%s\n' "$CONVENTIONS" >> "$OUT"
elif [ -f ".agentic/conventions.md" ]; then
  printf '\n## Project conventions\n\n' >> "$OUT"
  cat .agentic/conventions.md >> "$OUT"
fi

# ── Build commands ────────────────────────────────────────────────────────────
printf '\n## Build commands\n' >> "$OUT"
[ -n "${BUILD_CHECK:-}" ] && printf 'Check: %s\n' "$BUILD_CHECK" >> "$OUT"
[ -n "${BUILD_TEST:-}"  ] && printf 'Test:  %s\n' "$BUILD_TEST"  >> "$OUT"
[ -f ".agentic/build.sh" ] && printf 'Or run: .agentic/build.sh check|test\n' >> "$OUT"

# ── Task instructions ─────────────────────────────────────────────────────────
cat >> "$OUT" << EOF

## Your task
1. Read the issue body below and understand the problem fully before touching any file
2. Make the minimal correct fix -- no refactoring beyond what the issue requires
3. Run the build check command (0 warnings) then the test command
4. Commit: git commit -S -m '<type>(<scope>): <description>'
5. Push: git push origin ${BRANCH}
6. Open PR against main with: gh pr create --title '...' --body 'Fixes #${ISSUE_NUMBER}. ...'
7. Update issue label: gh issue edit ${ISSUE_NUMBER} --remove-label agent-coding --add-label agent-review

If you hit an ambiguity that blocks you, post a comment on the issue explaining what is unclear, then stop.

## Issue Body

${ISSUE_BODY}
EOF
